version: "3.8"

services:
  mysql:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: curtaincall
        TZ: Asia/Seoul
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci