spring:
  application:
    name: curtaincall-web

  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  mvc:
    problemdetails:
      enabled: true

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
    open-in-view: false

  sql:
    init:
      mode: never

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-id: ${OAUTH2_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope: ~
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  kopis:
    service-key: ${KOPIS_SERVICE_KEY}
  jwt:
    secret: ${JWT_SECRET}
    access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}
    refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/curtaincall?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm.jdbc.bind: trace
      apache.coyote.http11: debug

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL_PROD}
    username: ${DATABASE_USERNAME_PROD}
    password: ${DATABASE_PASSWORD_PROD}

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://curtaincall.ap-northeast-2.elasticbeanstalk.com:8080/login/oauth2/code/kakao

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

app:
  s3:
    bucket-name: ${AWS_S3_BUCKET}