spring:

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
    open-in-view: false

  batch:
    job:
      enabled: true
      name: ${job.name:NONE}
    jdbc:
      initialize-schema: never
      isolation-level-for-create: default

logging:
  level:
    org.cmc.curtaincall: debug
#    org:
#      hibernate:
#        SQL: debug
#        orm.jdbc.bind: trace

app:
  kopis:
    base-url: "http://www.kopis.or.kr"
    service-key: ${KOPIS_SERVICE_KEY}
